version: '2.4'

services:
  app:
    container_name: yt
    restart: on-failure
    user: "1000:1000"
    build:
      context: .
      dockerfile: Dockerfile.development
    command: npm run dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "${PORT}:8080"
    deploy:
      resources:
        limits:
          memory: 4096M
        reservations:
          memory: 256M

